-- CAT-019 Código de Actividad Económica (El Salvador DTE - MH)
-- Basado en CIIU Rev.4 adaptado para El Salvador
-- Ejecutar una vez: psql -d <db> -f cat_actividad_economica.sql

CREATE TABLE IF NOT EXISTS cat_actividad_economica (
    codigo      VARCHAR(10) PRIMARY KEY,
    descripcion VARCHAR(250) NOT NULL
);

INSERT INTO cat_actividad_economica (codigo, descripcion) VALUES
-- A: Agricultura, ganadería, silvicultura y pesca
('01110','Cultivo de cereales'),
('01120','Cultivo de leguminosas'),
('01130','Cultivo de oleaginosas'),
('01140','Cultivo de tabaco'),
('01150','Cultivo de plantas para preparar bebidas'),
('01160','Cultivo de plantas aromáticas y medicinales'),
('01190','Cultivo de otras plantas no perennes'),
('01210','Cultivo de uva'),
('01220','Cultivo de frutas tropicales y subtropicales'),
('01230','Cultivo de cítricos'),
('01240','Cultivo de frutas de pepita y de hueso'),
('01250','Cultivo de otros frutos'),
('01260','Cultivo de frutas oleaginosas'),
('01270','Cultivo de plantas para preparar bebidas (perennes)'),
('01280','Cultivo de especias, plantas aromáticas y medicinales'),
('01290','Cultivo de otras plantas perennes'),
('01300','Propagación de plantas'),
('01410','Cría de ganado bovino y búfalo'),
('01420','Cría de caballos y otros equinos'),
('01440','Cría de ovejas y cabras'),
('01450','Cría de porcinos'),
('01460','Cría de aves de corral'),
('01490','Cría de otros animales'),
('01500','Explotación mixta (agricultura y ganadería)'),
('01610','Actividades de apoyo a la agricultura'),
('01620','Actividades de apoyo a la ganadería'),
('01630','Actividades poscosecha'),
('01640','Tratamiento de semillas para propagación'),
('01700','Caza ordinaria y mediante trampas'),
('02100','Silvicultura y otras actividades forestales'),
('02200','Extracción de madera'),
('02300','Recolección de productos forestales distintos de la madera'),
('02400','Servicios de apoyo a la silvicultura'),
('03110','Pesca marítima'),
('03120','Pesca de agua dulce'),
('03210','Acuicultura marítima'),
('03220','Acuicultura de agua dulce'),
-- B: Explotación de minas y canteras
('05100','Extracción de hulla'),
('06100','Extracción de petróleo crudo'),
('06200','Extracción de gas natural'),
('07100','Extracción de minerales de hierro'),
('07290','Extracción de otros minerales metalíferos no ferrosos'),
('08110','Extracción de piedra, arena y arcilla'),
('08910','Extracción de minerales para la fabricación de abonos'),
('08990','Explotación de otras minas y canteras'),
('09100','Actividades de apoyo para la extracción de petróleo y gas natural'),
('09900','Actividades de apoyo para otras actividades de explotación de minas'),
-- C: Industrias manufactureras
('10110','Procesamiento y conservación de carne'),
('10120','Procesamiento y conservación de carne de aves'),
('10130','Elaboración de productos cárnicos'),
('10201','Procesamiento y conservación de camarones'),
('10202','Procesamiento y conservación de pescado'),
('10203','Procesamiento y conservación de mariscos'),
('10310','Elaboración y conservación de frutas'),
('10320','Elaboración de jugos de frutas y hortalizas'),
('10330','Elaboración de aceites y grasas de origen vegetal'),
('10501','Elaboración de leche pasteurizada'),
('10502','Elaboración de queso'),
('10503','Elaboración de otros derivados lácteos'),
('10610','Elaboración de productos de molinería'),
('10620','Elaboración de almidones y productos derivados'),
('10710','Elaboración de productos de panadería'),
('10720','Elaboración de azúcar'),
('10730','Elaboración de cacao, chocolate y productos de confitería'),
('10740','Elaboración de pastas alimenticias y fideos'),
('10750','Elaboración de comidas y platos preparados'),
('10790','Elaboración de otros productos alimenticios'),
('10800','Elaboración de alimentos preparados para animales'),
('11010','Destilación, rectificación y mezcla de bebidas alcohólicas'),
('11020','Elaboración de vinos'),
('11030','Elaboración de bebidas malteadas y de malta'),
('11040','Elaboración de bebidas no alcohólicas; producción de aguas minerales'),
('12000','Elaboración de productos del tabaco'),
('13100','Preparación e hilatura de fibras textiles'),
('13200','Tejeduría de productos textiles'),
('13300','Acabado de productos textiles'),
('13910','Fabricación de tejidos de punto y ganchillo'),
('13920','Fabricación de artículos confeccionados de materiales textiles'),
('13990','Fabricación de otros productos textiles'),
('14100','Fabricación de prendas de vestir'),
('14200','Fabricación de artículos de piel'),
('14300','Fabricación de artículos de punto y ganchillo'),
('15110','Curtido y adobo de cueros; curtido y adobo de pieles'),
('15120','Fabricación de maletas, bolsos de mano y artículos similares'),
('15200','Fabricación de calzado'),
('16100','Aserrado y acepillado de madera'),
('16210','Fabricación de hojas de madera para enchapado'),
('16220','Fabricación de parquet ensamblado para pisos'),
('16230','Fabricación de otros productos de madera'),
('16240','Fabricación de envases de madera'),
('16290','Fabricación de otros productos de madera y artículos de corcho'),
('17110','Fabricación de pasta de madera, papel y cartón'),
('17120','Fabricación de papel y cartón'),
('17210','Fabricación de envases de papel y cartón'),
('17220','Fabricación de productos de papel y cartón de uso doméstico'),
('17230','Fabricación de artículos de papel y cartón de escritorio'),
('17290','Fabricación de otros artículos de papel y cartón'),
('18110','Impresión'),
('18120','Actividades de servicios relacionados con la impresión'),
('18200','Reproducción de grabaciones'),
('19200','Fabricación de productos de la refinación del petróleo'),
('20110','Fabricación de gases industriales'),
('20120','Fabricación de colorantes y pigmentos'),
('20130','Fabricación de otros productos químicos inorgánicos básicos'),
('20140','Fabricación de otros productos químicos orgánicos básicos'),
('20150','Fabricación de abonos y compuestos de nitrógeno'),
('20160','Fabricación de plásticos en formas primarias'),
('20200','Fabricación de pesticidas y otros productos agroquímicos'),
('20300','Fabricación de pinturas, barnices y productos de revestimiento similares'),
('20410','Fabricación de jabones y detergentes'),
('20420','Fabricación de perfumes y preparados de tocador'),
('20590','Fabricación de otros productos químicos'),
('20600','Fabricación de fibras artificiales'),
('21100','Fabricación de productos farmacéuticos básicos'),
('21200','Fabricación de medicamentos y otros productos farmacéuticos'),
('22110','Fabricación de cubiertas y cámaras de caucho'),
('22190','Fabricación de otros productos de caucho'),
('22210','Fabricación de placas, hojas, tubos y perfiles de plástico'),
('22220','Fabricación de embalajes de plástico'),
('22230','Fabricación de artículos de plástico para la construcción'),
('22290','Fabricación de otros productos de plástico'),
('23110','Fabricación de vidrio plano'),
('23130','Fabricación de vidrio hueco'),
('23190','Fabricación y elaboración de otros artículos de vidrio'),
('23310','Fabricación de azulejos y losas de cerámica'),
('23320','Fabricación de ladrillos, tejas y productos de construcción en arcilla cocida'),
('23410','Fabricación de artículos domésticos y ornamentales de cerámica'),
('23420','Fabricación de aparatos sanitarios de cerámica'),
('23490','Fabricación de otros productos cerámicos'),
('23510','Fabricación de cemento'),
('23520','Fabricación de cal y yeso'),
('23610','Fabricación de productos de hormigón para la construcción'),
('23620','Fabricación de productos de yeso para la construcción'),
('23630','Fabricación de hormigón fresco'),
('23640','Fabricación de mortero'),
('23690','Fabricación de otros artículos de hormigón, yeso y cemento'),
('23700','Corte, tallado y acabado de la piedra'),
('23900','Fabricación de otros productos minerales no metálicos'),
('24100','Industrias básicas de hierro y acero'),
('24200','Fabricación de tubos, tuberías, perfiles huecos y accesorios de acero'),
('24310','Estirado en frío de barras'),
('24420','Producción de aluminio'),
('24440','Producción de cobre'),
('24450','Producción de otros metales no ferrosos'),
('24510','Fundición de hierro y acero'),
('24520','Fundición de metales no ferrosos'),
('25110','Fabricación de construcciones metálicas y sus partes'),
('25120','Fabricación de cisternas, grandes depósitos y contenedores de metal'),
('25200','Fabricación de armas y municiones'),
('25910','Fabricación de productos metálicos forjados y prensados'),
('25920','Tratamiento y revestimiento de metales'),
('25930','Fabricación de artículos de cuchillería y herramientas de mano'),
('25990','Fabricación de otros productos elaborados de metal'),
('26100','Fabricación de componentes y tableros electrónicos'),
('26200','Fabricación de computadoras y equipo periférico'),
('26300','Fabricación de equipos de comunicaciones'),
('26400','Fabricación de aparatos electrónicos de consumo'),
('26510','Fabricación de instrumentos y aparatos para medir, verificar y navegar'),
('26520','Fabricación de relojes'),
('26600','Fabricación de equipos de irradiación y equipo electrónico de uso médico'),
('26700','Fabricación de instrumentos ópticos y equipo fotográfico'),
('27100','Fabricación de motores, generadores, transformadores eléctricos'),
('27200','Fabricación de pilas, baterías y acumuladores'),
('27400','Fabricación de equipos eléctricos de iluminación'),
('27500','Fabricación de aparatos de uso doméstico'),
('27900','Fabricación de otros tipos de equipo eléctrico'),
('28110','Fabricación de motores y turbinas'),
('28130','Fabricación de otras bombas, compresores, grifos y válvulas'),
('28150','Fabricación de hornos, hogares y quemadores industriales'),
('28160','Fabricación de equipo de elevación y manipulación'),
('28170','Fabricación de maquinaria y equipo de oficina'),
('28190','Fabricación de otros tipos de maquinaria de uso general'),
('28210','Fabricación de maquinaria agropecuaria y forestal'),
('28220','Fabricación de máquinas herramienta'),
('28250','Fabricación de maquinaria para elaborar alimentos, bebidas y tabaco'),
('28260','Fabricación de maquinaria para elaborar textiles, prendas de vestir y cuero'),
('28290','Fabricación de otros tipos de maquinaria de uso especial'),
('29100','Fabricación de vehículos automotores'),
('29200','Fabricación de carrocerías para vehículos automotores; remolques'),
('29300','Fabricación de partes, piezas y accesorios para vehículos automotores'),
('30110','Construcción de barcos y estructuras flotantes'),
('30120','Construcción de embarcaciones de recreo y deporte'),
('30300','Fabricación de aeronaves, naves espaciales y maquinaria relacionada'),
('30910','Fabricación de motocicletas'),
('30920','Fabricación de bicicletas y vehículos de tracción humana'),
('30990','Fabricación de otros tipos de equipo de transporte'),
('31001','Fabricación de muebles de madera'),
('31002','Fabricación de muebles metálicos'),
('31003','Fabricación de muebles de plástico'),
('32110','Fabricación de joyas y artículos conexos'),
('32120','Fabricación de bisutería y artículos conexos'),
('32200','Fabricación de instrumentos musicales'),
('32300','Fabricación de artículos de deporte'),
('32400','Fabricación de juegos y juguetes'),
('32500','Fabricación de instrumentos y materiales médicos y odontológicos'),
('32910','Fabricación de escobas, brochas y cepillos'),
('32990','Otras industrias manufactureras n.c.p.'),
('33110','Reparación de productos metálicos elaborados'),
('33120','Reparación de maquinaria'),
('33130','Reparación de equipo electrónico y óptico'),
('33140','Reparación de equipo eléctrico'),
('33150','Reparación y mantenimiento de barcos y embarcaciones'),
('33160','Reparación y mantenimiento de aeronaves y naves espaciales'),
('33170','Reparación y mantenimiento de otros equipos de transporte'),
('33190','Reparación de otros equipos'),
('33200','Instalación de maquinaria y equipos industriales'),
-- D: Suministro de electricidad, gas, vapor
('35100','Generación, transmisión y distribución de energía eléctrica'),
('35200','Fabricación de gas; distribución de combustibles gaseosos por tuberías'),
('35300','Suministro de vapor y de aire acondicionado'),
-- E: Suministro de agua
('36000','Captación, tratamiento y distribución de agua'),
('37000','Evacuación y tratamiento de aguas residuales'),
('38110','Recogida de desechos no peligrosos'),
('38120','Recogida de desechos peligrosos'),
('38210','Tratamiento y eliminación de desechos no peligrosos'),
('38220','Tratamiento y eliminación de desechos peligrosos'),
('38300','Recuperación de materiales'),
('39000','Actividades de saneamiento y otros servicios de gestión de desechos'),
-- F: Construcción
('41001','Construcción de edificios residenciales'),
('41002','Construcción de edificios no residenciales'),
('42101','Construcción de carreteras y calles'),
('42102','Construcción de vías de ferrocarril'),
('42200','Construcción de proyectos de servicio público'),
('42901','Construcción de obras hidráulicas'),
('42902','Otras actividades especializadas de construcción'),
('43110','Demolición'),
('43120','Preparación del terreno'),
('43130','Perforación y sondeo'),
('43210','Instalaciones eléctricas'),
('43220','Instalaciones de plomería, calefacción y aire acondicionado'),
('43290','Otras instalaciones para obras de construcción'),
('43310','Instalación de revestimientos de pisos y paredes'),
('43320','Instalación de carpintería'),
('43330','Revestimiento de pisos y paredes'),
('43340','Pintura y acristalamiento'),
('43390','Otras obras de acabado'),
('43910','Actividades especializadas de construcción n.c.p.'),
('43990','Otras actividades especializadas de construcción'),
-- G: Comercio al por mayor y menor
('45101','Venta de vehículos automotores nuevos'),
('45102','Venta de vehículos automotores usados'),
('45200','Mantenimiento y reparación de vehículos automotores'),
('45301','Venta al por mayor de partes y piezas para vehículos'),
('45302','Venta al por menor de partes y piezas para vehículos'),
('45400','Venta, mantenimiento y reparación de motocicletas y sus partes'),
('46100','Venta al por mayor a cambio de una retribución o por contrata'),
('46200','Venta al por mayor de materias primas agropecuarias y animales vivos'),
('46310','Venta al por mayor de frutas, legumbres y hortalizas'),
('46320','Venta al por mayor de carne y productos cárnicos'),
('46330','Venta al por mayor de productos lácteos, huevos y aceites comestibles'),
('46340','Venta al por mayor de bebidas'),
('46350','Venta al por mayor de productos del tabaco'),
('46360','Venta al por mayor de azúcar'),
('46370','Venta al por mayor de café, té, cacao y especias'),
('46380','Venta al por mayor de pescado, crustáceos y moluscos'),
('46390','Venta al por mayor de otros alimentos'),
('46410','Venta al por mayor de textiles'),
('46420','Venta al por mayor de prendas de vestir y calzado'),
('46430','Venta al por mayor de artículos eléctricos y electrónicos'),
('46440','Venta al por mayor de porcelana, cristalería y productos de limpieza'),
('46450','Venta al por mayor de perfumes y cosméticos'),
('46460','Venta al por mayor de productos farmacéuticos'),
('46470','Venta al por mayor de muebles y colchones'),
('46480','Venta al por mayor de relojes y artículos de joyería'),
('46490','Venta al por mayor de otros enseres domésticos'),
('46510','Venta al por mayor de computadoras, equipo periférico y programas'),
('46520','Venta al por mayor de equipo, partes y piezas electrónicas'),
('46610','Venta al por mayor de maquinaria y equipo agropecuarios'),
('46620','Venta al por mayor de máquinas herramienta'),
('46630','Venta al por mayor de maquinaria para la minería, construcción e ingeniería civil'),
('46640','Venta al por mayor de maquinaria para la industria de la construcción'),
('46650','Venta al por mayor de maquinaria de oficina'),
('46660','Venta al por mayor de otros tipos de maquinaria y equipo industrial'),
('46691','Venta al por mayor de combustibles sólidos, líquidos y gaseosos'),
('46692','Venta al por mayor de metales y minerales metalíferos'),
('46693','Venta al por mayor de materiales de construcción y artículos de ferretería'),
('46694','Venta al por mayor de productos químicos y conexos'),
('46695','Venta al por mayor de desperdicios y desechos'),
('46699','Venta al por mayor de otros productos no especificados'),
('46900','Venta al por mayor no especializada'),
('47110','Venta al por menor en comercios no especializados con predominio de alimentos'),
('47190','Otras actividades de venta al por menor en comercios no especializados'),
('47210','Venta al por menor de frutas y verduras frescas'),
('47220','Venta al por menor de carne y productos cárnicos'),
('47230','Venta al por menor de pescado, crustáceos y moluscos'),
('47240','Venta al por menor de pan, pasteles, confitería y golosinas'),
('47250','Venta al por menor de bebidas'),
('47260','Venta al por menor de tabaco'),
('47290','Otras actividades de venta al por menor de alimentos en comercios especializados'),
('47300','Venta al por menor de combustible para vehículos automotores'),
('47411','Venta al por menor de computadoras, unidades periféricas y software'),
('47412','Venta al por menor de equipo de telecomunicaciones'),
('47413','Venta al por menor de equipo de sonido y video'),
('47510','Venta al por menor de textiles'),
('47521','Venta al por menor de ferretería, pinturas y productos de vidrio'),
('47522','Venta al por menor de material de construcción'),
('47530','Venta al por menor de alfombras, tapices y cubrimiento de pisos'),
('47540','Venta al por menor de electrodomésticos'),
('47591','Venta al por menor de muebles'),
('47592','Venta al por menor de artículos para alumbrado'),
('47593','Venta al por menor de artículos para el hogar'),
('47611','Venta al por menor de libros'),
('47612','Venta al por menor de papelería y artículos de escritorio'),
('47613','Venta al por menor de productos de música y video'),
('47620','Venta al por menor de artículos de deporte'),
('47630','Venta al por menor de juegos y juguetes'),
('47641','Venta al por menor de prendas de vestir'),
('47642','Venta al por menor de artículos de cuero y afines'),
('47643','Venta al por menor de calzado'),
('47711','Venta al por menor de productos farmacéuticos'),
('47712','Venta al por menor de artículos médicos y ortopédicos'),
('47713','Venta al por menor de artículos de tocador y perfumería'),
('47721','Venta al por menor de plantas y flores'),
('47722','Venta al por menor de animales y alimentos para mascotas'),
('47730','Venta al por menor de combustible para uso doméstico'),
('47740','Venta al por menor de equipo de audio y video'),
('47750','Venta al por menor de artículos de segunda mano'),
('47810','Venta al por menor en puestos de venta y mercados de alimentos, bebidas y tabaco'),
('47820','Venta al por menor en puestos de venta y mercados de textiles'),
('47890','Venta al por menor en puestos de venta y mercados de otros productos'),
('47910','Venta al por menor por correo y por Internet'),
('47990','Otras actividades de venta al por menor no realizadas en comercios, puestos de venta o mercados'),
-- H: Transporte y almacenamiento
('49100','Transporte por vía férrea de pasajeros'),
('49200','Transporte de carga por vía férrea'),
('49310','Transporte urbano y suburbano de pasajeros por vía terrestre'),
('49320','Transporte de pasajeros en taxis'),
('49391','Transporte de pasajeros por vía terrestre interurbano'),
('49392','Otras formas de transporte por vía terrestre'),
('49400','Transporte de carga por carretera'),
('49500','Transporte por tuberías'),
('50101','Transporte marítimo de pasajeros'),
('50102','Transporte marítimo de carga'),
('51100','Transporte aéreo de pasajeros'),
('51200','Transporte aéreo de carga'),
('52101','Almacenamiento y depósito'),
('52102','Servicios frigoríficos'),
('52210','Actividades de servicios vinculadas al transporte terrestre'),
('52220','Actividades de servicios vinculadas al transporte acuático'),
('52230','Actividades de servicios vinculadas al transporte aéreo'),
('52240','Manipulación de la carga'),
('52290','Otras actividades de apoyo al transporte'),
('53100','Actividades postales nacionales'),
('53200','Actividades de mensajería'),
-- I: Actividades de alojamiento y servicio de comidas
('55100','Hoteles y establecimientos similares'),
('55201','Alojamientos para vacaciones y viviendas de uso turístico'),
('55202','Hostales y pensiones'),
('55900','Otros tipos de alojamiento temporal'),
('56101','Restaurantes y actividades móviles de servicio de comidas'),
('56102','Bares y cantinas'),
('56210','Suministro de comidas por encargo (catering)'),
('56290','Otras actividades de servicio de comidas'),
('56300','Actividades de venta de bebidas'),
-- J: Información y comunicaciones
('58110','Edición de libros'),
('58120','Edición de directorios y listas de correo'),
('58130','Edición de periódicos, diarios y revistas'),
('58190','Otras actividades de edición'),
('58200','Edición de programas informáticos'),
('59110','Producción de películas cinematográficas, vídeos y programas de televisión'),
('59120','Actividades de postproducción de películas cinematográficas'),
('59130','Distribución de películas cinematográficas, vídeos y programas de televisión'),
('59140','Proyección de películas cinematográficas'),
('59200','Actividades de grabación de sonido y edición de música'),
('60100','Transmisiones de radio'),
('60200','Programación y transmisiones de televisión'),
('61100','Actividades de telecomunicaciones alámbricas'),
('61200','Actividades de telecomunicaciones inalámbricas'),
('61300','Actividades de telecomunicaciones por satélite'),
('61900','Otras actividades de telecomunicaciones'),
('62010','Actividades de programación informática'),
('62020','Actividades de consultoría informática'),
('62090','Otras actividades de tecnología de la información'),
('63110','Procesamiento de datos, hospedaje y actividades conexas'),
('63120','Portales web'),
('63910','Actividades de agencias de noticias'),
('63990','Otras actividades de servicios de información'),
-- K: Actividades financieras y de seguros
('64110','Banca central'),
('64190','Otras actividades de intermediación monetaria'),
('64201','Actividades de sociedad de cartera'),
('64202','Actividades de fideicomiso y fondos'),
('64910','Arrendamiento financiero'),
('64921','Actividades de crédito hipotecario'),
('64922','Actividades de crédito prendario'),
('64929','Otras actividades de concesión de crédito'),
('64990','Otras actividades de servicios financieros'),
('65110','Seguros de vida'),
('65120','Seguros distintos de los de vida'),
('65200','Reaseguros'),
('65300','Fondos de pensiones'),
('66110','Administración de mercados financieros'),
('66120','Corretaje de valores y de contratos de productos básicos'),
('66190','Otras actividades auxiliares de las actividades de servicios financieros'),
('66210','Evaluación de riesgos y daños'),
('66220','Actividades de agentes y corredores de seguros'),
('66290','Otras actividades auxiliares de las actividades de seguros'),
('66300','Actividades de gestión de fondos'),
-- L: Actividades inmobiliarias
('68100','Actividades inmobiliarias realizadas con bienes propios o arrendados'),
('68200','Actividades inmobiliarias realizadas a cambio de una retribución o por contrata'),
-- M: Actividades profesionales, científicas y técnicas
('69100','Actividades jurídicas'),
('69200','Actividades de contabilidad, teneduría de libros y auditoría'),
('70100','Actividades de oficinas principales'),
('70200','Actividades de consultoría de gestión empresarial'),
('71100','Actividades de arquitectura e ingeniería y actividades técnicas afines'),
('71200','Ensayos y análisis técnicos'),
('72100','Investigación y desarrollo experimental en ciencias naturales y exactas'),
('72200','Investigación y desarrollo experimental en ciencias sociales y humanidades'),
('73100','Publicidad'),
('73200','Estudios de mercado y encuestas de opinión pública'),
('74100','Actividades especializadas de diseño'),
('74200','Actividades de fotografía'),
('74900','Otras actividades profesionales, científicas y técnicas n.c.p.'),
('75000','Actividades veterinarias'),
-- N: Actividades de servicios administrativos y de apoyo
('77100','Alquiler y arrendamiento de vehículos automotores'),
('77210','Alquiler y arrendamiento de equipo recreativo y deportivo'),
('77220','Alquiler de videos y discos'),
('77230','Alquiler de otros efectos personales y artículos para el hogar'),
('77290','Alquiler de otros artículos de uso personal y doméstico'),
('77300','Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles'),
('77400','Arrendamiento de propiedad intelectual y productos similares'),
('78100','Actividades de agencias de empleo'),
('78200','Actividades de agencias de empleo temporal'),
('78300','Otras actividades de dotación de recursos humanos'),
('79110','Actividades de agencias de viaje'),
('79120','Actividades de operadores turísticos'),
('79900','Otros servicios de reservas y actividades conexas'),
('80100','Actividades de seguridad privada'),
('80200','Actividades de sistemas de seguridad'),
('80300','Actividades de investigación'),
('81100','Actividades combinadas de apoyo a instalaciones'),
('81210','Limpieza general de edificios'),
('81290','Otras actividades de limpieza de edificios e instalaciones'),
('81300','Actividades de paisajismo y servicios de mantenimiento conexos'),
('82110','Actividades combinadas de servicios administrativos de oficina'),
('82190','Fotocopiado, preparación de documentos y otras actividades especializadas'),
('82200','Actividades de centros de llamadas (call centers)'),
('82300','Organización de convenciones y exposiciones comerciales'),
('82910','Actividades de agencias de cobro y agencias de calificación crediticia'),
('82920','Actividades de envasado y empaque'),
('82990','Otras actividades de servicio de apoyo a las empresas n.c.p.'),
-- O: Administración pública y defensa
('84110','Actividades de administración pública en general'),
('84120','Regulación de las actividades de organismos que prestan servicios sanitarios y educativos'),
('84130','Regulación y facilitación de la actividad económica'),
('84210','Relaciones exteriores'),
('84220','Actividades de defensa'),
('84230','Actividades de mantenimiento del orden público y de seguridad'),
('84240','Actividades de justicia'),
('84250','Actividades de protección civil'),
('84260','Actividades de seguridad social de afiliación obligatoria'),
-- P: Educación
('85100','Enseñanza preescolar'),
('85200','Enseñanza primaria'),
('85310','Enseñanza secundaria de formación general'),
('85320','Enseñanza secundaria de formación técnica y profesional'),
('85410','Enseñanza post-secundaria no terciaria'),
('85420','Educación terciaria'),
('85491','Enseñanza de deportes y actividades recreativas'),
('85492','Enseñanza de cultura y artes'),
('85493','Enseñanza de manejo de vehículos'),
('85499','Otros tipos de enseñanza n.c.p.'),
('85500','Actividades de apoyo a la enseñanza'),
-- Q: Actividades de atención de la salud
('86101','Actividades de hospitales'),
('86102','Actividades de centros médicos'),
('86103','Actividades de clínicas médicas'),
('86200','Actividades de médicos y odontólogos'),
('86901','Actividades de laboratorios clínicos'),
('86902','Actividades de ambulancias'),
('86903','Actividades de centros de salud'),
('86909','Otras actividades de atención de la salud humana'),
('87100','Actividades de atención de enfermería en instituciones'),
('87200','Actividades de tratamiento del abuso de sustancias'),
('87300','Actividades de atención en instituciones para personas de edad y discapacitadas'),
('87900','Otras actividades de atención en instituciones'),
('88100','Actividades de asistencia social sin alojamiento para personas de edad y discapacitadas'),
('88900','Otras actividades de asistencia social sin alojamiento'),
-- R: Actividades artísticas, de entretenimiento y recreativas
('90001','Actividades artísticas y de entretenimiento - artes escénicas'),
('90002','Actividades artísticas y de entretenimiento - otras artes'),
('91010','Actividades de bibliotecas y archivos'),
('91020','Actividades de museos'),
('91030','Actividades de lugares y edificios históricos'),
('91040','Actividades de jardines botánicos, zoológicos y reservas naturales'),
('92000','Actividades de juegos de azar y apuestas'),
('93110','Gestión de instalaciones deportivas'),
('93120','Actividades de clubes deportivos'),
('93130','Actividades de gimnasios'),
('93191','Actividades de patrocinadores de deportes'),
('93192','Otras actividades deportivas'),
('93210','Actividades de parques de atracciones y parques temáticos'),
('93290','Otras actividades de esparcimiento y recreación n.c.p.'),
-- S: Otras actividades de servicios
('94110','Actividades de organizaciones empresariales y de empleadores'),
('94120','Actividades de organizaciones profesionales'),
('94200','Actividades de sindicatos'),
('94910','Actividades de organizaciones religiosas'),
('94920','Actividades de organizaciones políticas'),
('94990','Actividades de otras asociaciones n.c.p.'),
('95110','Reparación de computadoras y equipo periférico'),
('95120','Reparación de equipos de comunicación'),
('95210','Reparación de aparatos electrónicos de consumo'),
('95220','Reparación de electrodomésticos y equipo para el hogar y el jardín'),
('95230','Reparación de calzado y artículos de cuero'),
('95240','Reparación de muebles y artículos para el hogar'),
('95290','Reparación de otros efectos personales y enseres domésticos'),
('96010','Lavado y limpieza de prendas de tela y de piel'),
('96020','Peluquería y otros tratamientos de belleza'),
('96030','Actividades funerarias y conexas'),
('96040','Actividades de mantenimiento corporal'),
('96090','Otras actividades de servicios personales n.c.p.'),
-- T: Actividades de los hogares
('97000','Actividades de los hogares como empleadores de personal doméstico'),
('98100','Actividades de los hogares como productores de bienes para uso propio'),
('98200','Actividades de los hogares como productores de servicios para uso propio')
ON CONFLICT (codigo) DO NOTHING;
